### ISSUE TITLE
Deploy a single-page app via CloudFront and S3 at secrettraitor.com

### ISSUE THREAD

**Issue by douglasnaphas** [secret-traitor/secret-traitor#14]
Accommodate the case where no name is specified. Use (and output) a CloudFront URL in that case. If, but only if, running locally, we'll have to add on an extra path ("/") from the Lambda backing the API that sends the SPA.

**Comment by douglasnaphas** [comment]
# TODO
- [ ] From the root of the project, run a `tsc` command to compile only `frontend/`.
- [ ] Deploy the frontend/ SPA to a CloudFront URL.
- [ ] Output the CloudFront URL from the stack.
- [ ] Take the domain name for the SPA as a param to `cdk`.
- [ ] Remove any mention of the domain name in `cdk.json`.
- [ ] Make sure the SPA can build locally with a `make` target, preferably from the root of the project.
- [ ] Make sure the SPA can run locally with a `make` target, preferably from the root of the project.

**Comment by douglasnaphas** [comment]
The objective here is to deploy our specific React app, the one that currently lives in `frontend/`, using the CDK code that has been moved to `deploy`. The deployment pipeline is currently failing.

**Comment by douglasnaphas** [comment]
@dan-muller Some subtle points [here](https://github.com/secret-traitor/secret-traitor/commit/ed93d376333f36149a65fdb9908e174a1d31b353#r45460750) about our distro-and-S3 combo.
