### ISSUE TITLE
Experiment with the crazy idea of no-local development

### ISSUE THREAD

**Issue by douglasnaphas** [secret-traitor/secret-traitor#28]
I want to try out developing with _no local dev at all_.

This is crazy, but I think it will be better.

A local dev env threatens to be a massive time suck. It requires:

1. Dockerfiles
2. a Docker Compose file
3. Nginx files to mimic CloudFront
4. mimicking DynamoDB with [dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local)
5. mimicking API Gateway WebSockets, not sure how
6. mimicking S3
7. mimicking Lambda
6. telling Cognito, once we want to have users who log in, that localhost is OK as a redirect URI
7. using [mkcert](https://github.com/FiloSottile/mkcert) so that we can use https://localhost
8. making annoying decisions about ports
9. constantly keeping in your head the various differences between local development and the live site.

The payoff for all of this is:

1. You _might_ be able to have React pages update without reloading.
2. You don't have to wait for a build to see changes.

I think the delay in seeing your changes is worth it. Especially since you don't have to commit to see changes--you can get your changes live by pushing to your development S3 bucket (for the frontend) or running `cdk deploy` from your local CLI (for everything else) between commits to a feature branch. And `cdk deploy` may often finish quickly, because CloudFormation will not deploy the entire stack with each deploy, but rather will only deploy the resources within the stack that have changed.

This Issue includes setting up a GitHub Actions build or builds so that you can

1. Fork this repo.
2. Add the credentials to your dev account in your fork as GitHub repository secrets.
3. Create a feature branch in your fork.
4. Have your feature branch automatically deployed to a CloudFront URL within the account targeted by your fork.

**Comment by douglasnaphas** [comment]
# TODO
- [x] Set up a feature branch build.
- [ ] Make our stack able to handle not having access to a domain name. [Here](https://github.com/douglasnaphas/secret-traitor/runs/1612897402?check_suite_focus=true) is an example of the kind of failure that needs to be fixed.
- [ ] Parameterize the stack name.
- [ ] Pass in the branch name to use in the stack name. That way I can have a stack named like `FeatureBranchATraitorStack` co-exist in my dev account with `FeatureBranchBTraitorStack`.
- [ ] Add `scripts` to `package.json` for dev inter-commit CDK diffing and deployment.

**Comment by dan-muller** [comment]
I was just thinking today how its very frustrating that local and prod are so different. I need to go over the details, but I love the idea.
