### ISSUE TITLE
Deploy to a staging environment and URL, and run tests against it

### ISSUE THREAD

**Issue by douglasnaphas** [secret-traitor/secret-traitor#8]
# TODO
- [x] Make an integration test script, parameterized on URL. Get it running locally for the prod URL(s).
- [x] Run the script from the pipeline after deployment.
- [ ] Make sure the whole stack is fully parameterized by site name (fully parameterize all domain names and CDK construct IDs).
- [ ] See how email aliases work, and whether I can use `+` to get a new AWS account (for the dev/staging account) without having to set up a new Gmail address.
- [ ] Add a parameter like STAGING (effectively a boolean, maybe, like treat it as true if it's defined), or use the env parameter that tells us whether it's running locally, to allow `cdk` commands to deploy to staging or prod. The stack should report no diff when this parameter indicates deployment to the prod env. Here setting up a dev account may actually be preferred.
- [ ] Deploy to our new staging URL traystay.net
